<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Le blog de l'AVBN</title>
        <link href="style.css" rel="stylesheet" />
    </head>
 
    <body>
      
 
        <h2>message</h2>
 
        <?php
        foreach ($messages as $row) {
        ?>
        <p><strong><?= htmlspecialchars($row['title']) ?></strong> le <?= $row['cretaedAt'] ?></p>
        <p><?= nl2br(htmlspecialchars($row['content'])) ?></p>
        <?php
        }
        ?>
    </body>
</html>