<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Le blog de l'AVBN</title>
        <link href="style.css" rel="stylesheet" />
    </head>
 
    <body>
      
        <h2>message</h2>
 
        <?php
        foreach ($messages as $message) {
        ?>
        <p> le <?= $message['cretaedAt']?></p>
        <p><?= $message['content']?></p>
        <?php
        
        }
        var_dump(messages);
        ?>
    </body>
</html>