<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Le blog de l'AVBN</title>
        <link href="style.css" rel="stylesheet" />
    </head>
 
    <body>
      
        <h2>message</h2>
 
        <?php
        foreach ($messages as $message) {
        ?>
     <?= ".$message['cretaedAt']. ?>
        <p><?= nl2br(htmlspecialchars($message['content'])) ?></p>
        <?php
        
        }
       
        ?>
    </body>
</html>