
</html>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="style.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>Document</title>
</head>

<body>

  <?php foreach ($messages as $message): ?>
    <div class="container">
      <div class="card mt-3">
        <div class="card-header d-flex justify-content-between p-3">
          <p class="fw-bold mb-0">
            
          </p>
        
          <p class="text-muted small mb-2"><i class="far fa-clock"></i><?php echo $message['createdAt'] ?></p>
          
             <!-- <a href="index.php?action=edit&messageId= $message[id]"class="btn btn-danger  ">Delete</a>  -->

             <a href="index.p^"class ="btn btn-success">Edit</a> 
          
          
        </div>
        <div class="card-body ">
          <p class="mb-0">
            <?php echo $message['content'] ?>
          </p>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
  <div class="container">
    <form action="index.php?action=addmessage" method="POST">
      <div class="flex-grow-0 py-3 px-4 border-top">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Type your message" id="content" name='content'>
          <button class="btn btn-primary" name="submit">Send</button>
        </div>
      </div>
    </form>
  </div>

  
</body>

</html>
<style>
  body {
    background-image: url("images/IMG_9800.JPG");
  }
</style>